tag_family:        'tagStandard41h12' 
tag_threads:       2          
tag_decimate:      1.0        
tag_blur:          0.0        
tag_refine_edges:  1          
tag_debug:         0          
max_hamming_dist:  2          
publish_tf:        true       
transport_hint:    "raw"      
